name: Update User Count

on:
  schedule:
    - cron: '17 17 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  update-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Cache: Cache Python"
        id: python-cache
        uses: actions/cache@v3.3.1
        with:
          path: ${{env.pythonLocation}}
          key: ${{env.pythonLocation}}-${{hashFiles('requirements.txt')}}
      - name: "Shell: Get pip cache dir"
        id: pip-cache-dir
        if: steps.python-cache.outputs.cache-hit != 'true'
        run: |
            python -m pip install -U pip
            pip install -U wheel
            echo "pip-cache-dir=$(pip cache dir)" >> ${GITHUB_OUTPUT}
      -   name: "Cache: Cache pip"
          if: steps.python-cache.outputs.cache-hit != 'true'
          uses: actions/cache@v3.3.1
          with:
              path: ${{steps.pip-cache-dir.outputs.pip-cache-dir}}
              key: 3.12-${{hashFiles('requirements.txt')}}
              restore-keys: |
                  3.12-${{hashFiles('requirements.txt')}}-
                  3.12-
      -   name: "Shell: Install pip dependencies"
          if: steps.python-cache.outputs.cache-hit != 'true'
          run: pip install -r requirements.txt

      - name: Scrape user count
        run: |
          python3 ./script/update-total-active-users.py

      - name: Commit user count change
        id: check_changes
        run: |
          set +e
          git diff --quiet
          if [[ $? -eq 1 ]]; then
            git config user.name 'github-actions[bot]'
            git config user.email 'keyz+github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "[Commit by bot] Update user count"
          else
            echo "The number of total active users hasn't changed."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
